## Task 1: Load and Explore

In [2]:
import pandas as pd
import numpy as np
import os

# Load data/trends_clean.csv into a Pandas DataFrame
df = pd.read_csv('trends_clean.csv')

# The 'data/' directory was not found, causing a FileNotFoundError.
# Listing the files directly in the current content directory.

print(os.listdir('.'))

# Print the first 5 rows
print("First 5 rows of the DataFrame:")
display(df.head())

# Print the shape of the DataFrame (rows and columns)
print(f"Shape of the DataFrame: {df.shape} (rows, columns)")

# Print the average score and average num_comments across all stories
average_score = df['score'].mean()
average_num_comments = df['num_comments'].mean()

print(f"Average Score: {average_score:.2f}")
print(f"Average Number of Comments: {average_num_comments:.2f}")

# What is the mean, median, and standard deviation of score?
score_mean = np.mean(df['score'])
score_median = np.median(df['score'])
score_std = np.std(df['score'])

print(f"Score - Mean: {score_mean:.2f}, Median: {score_median:.2f}, Standard Deviation: {score_std:.2f}")

# What is the highest score and lowest score?
highest_score = np.max(df['score'])
lowest_score = np.min(df['score'])

print(f"Highest Score: {highest_score}")
print(f"Lowest Score: {lowest_score}")

# Which category has the most stories?
most_stories_category = df['category'].value_counts().idxmax()
num_stories_in_category = df['category'].value_counts().max()

print(f"Category with the most stories: '{most_stories_category}' with {num_stories_in_category} stories.")

# Which story has the most comments? Print its title and comment count.
story_most_comments = df.loc[df['num_comments'].idxmax()]

print(f"Story with the most comments: '{story_most_comments['title']}' with {story_most_comments['num_comments']} comments.")


# Add 'engagement' column
df['engagement'] = df['num_comments'] / (df['score'] + 1)

# Add 'is_popular' column
df['is_popular'] = df['score'] > average_score

print("DataFrame with new 'engagement' and 'is_popular' columns:")
display(df.head())

# Save the updated DataFrame to data/trends_analysed.csv
df.to_csv('trends_analysed.csv', index=False)

# Print a confirmation message
print("Updated DataFrame saved to 'data/trends_analysed.csv'")

# Re-executing all code cells after fixing FileNotFoundError

# Cell 49f5289c: Load data
df = pd.read_csv('trends_clean.csv')

# Cell 72710dbb: Print first 5 rows
print("First 5 rows of the DataFrame:")
display(df.head())

# Cell a642b008: Print shape
print(f"Shape of the DataFrame: {df.shape} (rows, columns)")

# Cell 913db7f9: Print average score and comments (re-calculating average_score here)
average_score = df['score'].mean()
average_num_comments = df['num_comments'].mean()
print(f"Average Score: {average_score:.2f}")
print(f"Average Number of Comments: {average_num_comments:.2f}")

# Cell 47bd3a74: Mean, median, std of score
score_mean = np.mean(df['score'])
score_median = np.median(df['score'])
score_std = np.std(df['score'])
print(f"Score - Mean: {score_mean:.2f}, Median: {score_median:.2f}, Standard Deviation: {score_std:.2f}")

# Cell 68e395c9: Highest and lowest score
highest_score = np.max(df['score'])
lowest_score = np.min(df['score'])
print(f"Highest Score: {highest_score}")
print(f"Lowest Score: {lowest_score}")

# Cell 4b0e9aff: Category with most stories
most_stories_category = df['category'].value_counts().idxmax()
num_stories_in_category = df['category'].value_counts().max()
print(f"Category with the most stories: '{most_stories_category}' with {num_stories_in_category} stories.")

# Cell 88a4f978: Story with most comments
story_most_comments = df.loc[df['num_comments'].idxmax()]
print(f"Story with the most comments: '{story_most_comments['title']}' with {story_most_comments['num_comments']} comments.")

# Cell 220670d9: Add new columns
df['engagement'] = df['num_comments'] / (df['score'] + 1)
df['is_popular'] = df['score'] > average_score # Using average_score re-calculated above
print("DataFrame with new 'engagement' and 'is_popular' columns:")
display(df.head())

# Cell 20525d14: Save the result
df.to_csv('trends_analysed.csv', index=False)
print("Updated DataFrame saved to 'trends_analysed.csv'")

['.config', 'trends_clean.csv', 'sample_data']
First 5 rows of the DataFrame:

   post_id                  title  score  num_comments       category
0      1.0           Amazing Tech     10             5     technology
1      2.0      World News Update      6            10      worldnews
2      4.0   Science Breakthrough     15            20        science
3      6.0     Another Tech Story      7            12     technology
4      7.0  Entertainment Tonight     12             7  entertainment

Shape of the DataFrame: (5, 5) (rows, columns)
Average Score: 10.00
Average Number of Comments: 10.80
Score - Mean: 10.00, Median: 10.00, Standard Deviation: 3.29
Highest Score: 15
Lowest Score: 6
Category with the most stories: 'technology' with 2 stories.
Story with the most comments: 'Science Breakthrough' with 20 comments.
DataFrame with new 'engagement' and 'is_popular' columns:

,post_id,title,score,num_comments,category,engagement,is_popular
0,1.0,Amazing Tech,10,5,technology,0.454545,False
1,2.0,World News Update,6,10,worldnews,1.428571,False
2,4.0,Science Breakthrough,15,20,science,1.250000,True
3,6.0,Another Tech Story,7,12,technology,1.500000,False
4,7.0,Entertainment Tonight,12,7,entertainment,0.538462,True

Updated DataFrame saved to 'data/trends_analysed.csv'
First 5 rows of the DataFrame:

   post_id                  title  score  num_comments       category
0      1.0           Amazing Tech     10             5     technology
1      2.0      World News Update      6            10      worldnews
2      4.0   Science Breakthrough     15            20        science
3      6.0     Another Tech Story      7            12     technology
4      7.0  Entertainment Tonight     12             7  entertainment

Shape of the DataFrame: (5, 5) (rows, columns)
Average Score: 10.00
Average Number of Comments: 10.80
Score - Mean: 10.00, Median: 10.00, Standard Deviation: 3.29
Highest Score: 15
Lowest Score: 6
Category with the most stories: 'technology' with 2 stories.
Story with the most comments: 'Science Breakthrough' with 20 comments.
DataFrame with new 'engagement' and 'is_popular' columns:

,post_id,title,score,num_comments,category,engagement,is_popular
0,1.0,Amazing Tech,10,5,technology,0.454545,False
1,2.0,World News Update,6,10,worldnews,1.428571,False
2,4.0,Science Breakthrough,15,20,science,1.250000,True
3,6.0,Another Tech Story,7,12,technology,1.500000,False
4,7.0,Entertainment Tonight,12,7,entertainment,0.538462,True

Updated DataFrame saved to 'trends_analysed.csv'